
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: avito_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=avito_db
      - DB_USER=user
      - DB_PASSWORD=password

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    command: ["postgres://user:password@db:5432/avito_db?sslmode=disable", "up"]
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations

volumes:
  postgres_data: